= CrossyLane – Dokumentation
:toc:
:toclevels: 2
:sectnums:

== Ziel

Das Ziel dieses Projektes ist ein CrossRoad. Mit inspiration aus diesem Processing Spiel: https://openprocessing.org/@u115603/571637


== Vorgehen

Schritt 1: Initialisierung des Grundgerüsts mit 5 Lanes (evtl später mehr spurige lanes) einem Player der gegen unten und oben jumped zwischen den Lanes und auch links und rechts sich bewegen kann

Schritt 2: unlimitierte Lanes. Mit 5 Lanes im Screen aber per runtime immer wieder neu bauende Lanes so dass man unendlich nach oben gehen kann.

Schritt 3: Bewegende hindernisse auf den Lanes platzieren mit horizonatler geschwindigkeit

Schritt 4: HitBox erkennen. Eine kollision zwischen player und hinderniss führt zu gameOver. den GameOver screen müsste man auch erstellen.

Schritt 5: Kamera smooth mitziehen

Schritt 6: Score = höchste erreichte Lane

Schritt 7: Startscreen mit Score anzeige und play again

Schritt 8: Levels mir Random Logs und Cars und geschwindigkeit

Schritt 9: Animationen und Sounds, jump animations...


== Schwierigkeiten
- Kamera View: da musste man zuerst schauen, wie man die kamera überhaupt will im sinn von was soll im zentrum stehen. eine Schwierigkeit war es den spieler zwar im zentrum zu stellen, aber es immernoch so auszusehen lassen, als würd sich der spieler bewegen und nicht die Map.

== Lösungsweg
- Kamera View: zuerst war der Gedankengang, dass wen auf der Map die sachen sich bewegen dann wird es schon besser aussehen. aber der ansatz der auch im Inspirations Processing Game gebraucht wurde: Die kamere scrollte versetzt zum player. also mit leichtem delay zur bewegung des Spielers. Das habe ich mithilfe KI gelöst. unzwar nimmt man ein Target X nach jedem jump und pro frame kommt man immer näher ans target

== Endresultat

TODO: Was steht am Ende? Screenshots, Funktionsumfang, ggf. Link/Anleitung zum Starten.

== Lernerfolge / Reflexion
 - Direkt am Anfang lernte ich wie man das Projekt korekt aufsetzt. Wie man mit modulen umgeht und wie man ein Modul aus einem anderen Repo rüberkopiert ins eigene und es dann auch zum funktionieren zu bringen. ich brauchte 2 anläufe mit der Projekaufsetzung. auch waren paar depricated Sachen im pom.xml die ich angepasst habe.

- Ich hatte am Anfang keine Ahnung wie ich beginnen möchte, und habe mir deshalb mit Claude AI einen Plan überlegt wie ich es machen will. zusammen haben wir dann einen Schritt für Schritt plan entwickelt für eine erste Version, die ich in der doku als vorgehen schonmal dokumentiert habe.